### ISSUE TITLE
maxWidth

### ISSUE THREAD

**Issue by videophonegeek** [jbreckmckye/raphael-paragraph#4]
With x:10, maxWidth is respected:

var answer4 = paper.paragraph({x : 10, y : 96, maxWidth : 200, text : "SUPPOSE YOU COUGH, GO DOCTOR YOU?"});

This wraps as

SUPPOSE YOU COUGH,GO
DOCTOR YOU

But if you use a percentage for x:"10%" it wraps like this

SUPPOSE
YOU
COUGH,
GO
DOCTOR
YOU

**Comment by jbreckmckye** [comment]
I wasn't aware that plain Raphael shapes accepted string percentage widths as parameters - it's not mentioned in the docs - but as with the Raphael() constructor itself, it appears upon testing that they quietly do so.

I am a little wary of implementing this. There seem to be lots of implicit behaviours in Rapahel, and it's not clear how many are intentional. Matching each undocumented aspect could become a bit of a rabbit hole.

Still, I will take a look, see if there are any caveats, and think about it; perhaps this is useful enough that we just add it as a Raphael-Paragraph specific interface. I can certainly see how handy it'd be.

One obvious question, though: what is the expected behaviour of a percentage-sized paragraph when the viewbox is panned or resized?

**Comment by videophonegeek** [comment]
What I am hoping for is a responsive design where the paragraph will change the wrap as the area of the percentage expands and contracts. This helps with fixed window sized mobile devices when you flip portrait to landscape too.

**Comment by jbreckmckye** [comment]
As mentioned in the other issue, at present, the lines of a paragraph are not mutable; a dynamically responsive design must tear down paragraphs and regenerate them, or swap the visibility of two existing paragraphs.
