### ISSUE TITLE
onClick

### ISSUE THREAD

**Issue by videophonegeek** [jbreckmckye/raphael-paragraph#5]
Can you attach a handler to a click event on raphael-paragraph? This works with paper.text but not paper.paragraph.

var paper= Raphael("holder", "100%", "100%");  
var answer4 = paper.paragraph({x : 10, y : 96, maxWidth : 200, text : "SUPPOSE YOU COUGH, GO DOCTOR YOU?"});
answer4.node.onclick = function () {
    randomizeExit(answer4);
};

[Error] TypeError: undefined is not an object (evaluating 'answer4.node.onclick = function () {
    randomizeExit(answer4);
}')
    (anonymous function) (index.html, line 99)
    fire (jquery-2.1.4.js, line 3099)
    fireWith (jquery-2.1.4.js, line 3211)
    ready (jquery-2.1.4.js, line 3417)
    completed (jquery-2.1.4.js, line 3433)

**Comment by jbreckmckye** [comment]
You can - but not the way you're doing it.

The `node` handle you're using is a property of individual Raphael shapes, representing the actual vector element on the canvas. But a paragraph is not a shape - it is a _set_, a collection of shapes.

Rather than iterating through all members of the set and attaching handlers to their `node`s, though, you should simply use Raphael's `click` method, which is provided on shapes and sets alike.

(Honestly, I don't really know why Raphael even exposes `node`. It allows you to completely bypass Raphael's API and do all sorts of things that can break the legitimate interface. I would stick to the documented methods as far as possible.)

Now, there is one caveat, and it's one that was on my mind some time ago: when you attach click events to lines in a paragraph - by any method - it will attach events to each of the text elements, rather than a box 'enclosing' them. So, if you use a line-height to create extra vertical spacing between lines, then clicks might pass through those gaps, because you aren't actually _clicking_ on any of the actual shapes, per se.

I did think about attaching a transparent background element to paragraphs that would intercept all pointer events - and possibly exceed the text's edges, too. Doing it this way might break glows unless I intercepted certain method calls, though. Let me know if it's important and I shall have a think.

**Comment by videophonegeek** [comment]
Much more convenient to have one handler attach to all the lines. What would happen if the paragraph resized and the number of lines changed.  At notification is needed to expire the old handlers and attach new ones.

**Comment by jbreckmckye** [comment]
The lines of a paragraph are not (presently) mutable; if they need to fit new dimensions, you need to destroy and regenerate them with new parameters. So .click() should fit your purposes, for the moment, at least.
